/// A tradução de um slug do Flocks para o nome no Phosphor.
///
/// Os dois vocabulários não coincidem: o Flocks chama `chevron-down` o que o
/// Phosphor chama `caret-down`, e `error-circle` o que ele chama
/// `warning-circle`. Sem esta tabela, o contrato de `AppIconToken` não
/// desenharia — que é justamente o que este pacote precisa entregar.
///
/// Só as divergências entram. Slug ausente daqui é usado como está, e é isso
/// que dá acesso aos 1512 ícones do Phosphor pelo nome original: quem quiser
/// `airplane-tilt` escreve `airplane-tilt`, sem precisar de token.
///
/// GERADO de `packages/flocks/assets/icons/README.md`, que é onde a revisão
/// visual de cada par foi feita. Não edite à mão: corrija lá e regenere.
/// 30 dos 138 pares têm o mesmo nome nos dois lados e por isso não aparecem.
const Map<String, String> kFlocksToPhosphor = <String, String>{
  'account': 'user-circle',
  'accounts': 'users',
  'add': 'plus',
  'ai': 'robot',
  'ai-prompt-spark': 'magic-wand',
  'alert': 'warning',
  'api-cloud': 'cloud',
  'attachment': 'paperclip',
  'audio': 'file-audio',
  'automation': 'flow-arrow',
  'battery-voltage': 'battery-vertical-high',
  'bell-notification': 'bell-ringing',
  'brand': 'tag',
  'calendar': 'calendar-blank',
  'cancel': 'x-circle',
  'chat-add': 'chat-centered-dots',
  'chevron-down': 'caret-down',
  'chevron-left': 'caret-left',
  'chevron-right': 'caret-right',
  'chevron-up': 'caret-up',
  'client': 'user-list',
  'close': 'x',
  'collapse': 'sidebar-simple',
  'csv': 'file-csv',
  'dashboard': 'squares-four',
  'database-healthy': 'database',
  'database-history': 'clock-counter-clockwise',
  'database-unhealthy': 'database',
  'database-warning': 'database',
  'drag-arrow': 'arrows-out-cardinal',
  'driver': 'steering-wheel',
  'driver-ranking': 'ranking',
  'error-circle': 'warning-circle',
  'event': 'flag',
  'expand': 'sidebar',
  'external-link': 'arrow-square-out',
  'file-download': 'file-arrow-down',
  'filter': 'funnel',
  'filter-circle': 'funnel-simple',
  'general-dashboard': 'squares-four',
  'general-report': 'chart-bar',
  'geo-area': 'polygon',
  'graduation-hat': 'graduation-cap',
  'group': 'users-three',
  'hyperlink': 'link',
  'id-card': 'identification-card',
  'image-landscape': 'file-image',
  'import-assign': 'link-simple',
  'info-circle': 'info',
  'inventory': 'package',
  'light-bulb-shine': 'lightbulb',
  'link-broken': 'link-break',
  'live-feed': 'broadcast',
  'live-position': 'globe-hemisphere-west',
  'logout': 'sign-out',
  'mail': 'envelope',
  'map': 'map-trifold',
  'map-direction': 'map-pin-area',
  'map-marker': 'map-pin',
  'map-pin': 'map-pin-line',
  'maximize': 'corners-out',
  'media-video': 'video',
  'menu-vertical': 'dots-three-vertical',
  'minimize': 'corners-in',
  'models': 'tag-chevron',
  'module': 'puzzle-piece',
  'monitoring': 'monitor',
  'monitoring-events': 'monitor-play',
  'organizations': 'buildings',
  'pause': 'pause-circle',
  'pdf': 'file-pdf',
  'pencil': 'pencil-simple',
  'phone-settings': 'device-mobile',
  'phone-vibrate': 'vibrate',
  'play': 'play-circle',
  'policy': 'shield-check',
  'read-email-letter': 'envelope-open',
  'refresh': 'arrows-clockwise',
  'remove': 'minus',
  'report': 'files',
  'report-alert': 'warning-diamond',
  'report-finance': 'currency-circle-dollar',
  'report-sync': 'arrows-counter-clockwise',
  'rotate': 'arrow-clockwise',
  'search': 'magnifying-glass',
  'settings': 'gear',
  'settings-columns': 'columns',
  'slider-horizontal': 'sliders-horizontal',
  'speed': 'gauge',
  'stop': 'stop-circle',
  'support': 'headset',
  'swap-arrow': 'arrows-left-right',
  'sync': 'arrows-clockwise',
  'synchronize-refresh-arrow': 'arrows-clockwise',
  'system-healthy': 'check-circle',
  'system-unhealthy': 'x-circle',
  'system-warning': 'warning-circle',
  'tracker': 'cpu',
  'tracker-command': 'paper-plane-tilt',
  'travel': 'path',
  'upload-bottom': 'upload-simple',
  'user-mail': 'address-book',
  'users': 'users-three',
  'video-monitoring-events': 'film-strip',
  'video-play': 'file-video',
  'volume': 'speaker-high',
  'xls': 'file-xls',
  'zip-file': 'file-zip',
};
