// O vocabulário fechado de `states` e `variants` do catálogo.
//
// Estes dois campos não são bilíngues: nomeiam superfície de API — o valor de
// um enum, um estado de interação —, e o vocabulário dessa camada é inglês em
// todo o pacote. Publicados como estão nas rotas PT e EN do site.
//
// É uma allow-list, e não uma heurística, porque a heurística FALHOU no
// canário: `repouso` não tem acento e passou batido por uma varredura de
// acento + palavras funcionais. Token de estado é curto e sem acento por
// natureza — é o pior caso possível para adivinhação. Aqui, um valor novo é um
// diff nesta lista, que alguém lê.
//
// Para acrescentar um estado: escreva-o em inglês, no mesmo estilo dos
// vizinhos (minúsculas, hífen entre palavras, parêntese para a condição), e
// acrescente-o aqui.

/// Estados de interação aceitos em `AppComponentMeta.states`.
const Set<String> kComponentStates = <String>{
  'active',
  'active-dot',
  'adjacent-items',
  'api-only',
  'at-max',
  'at-min',
  'below-min (disabled)',
  'both',
  'bottom-hidden',
  'busy',
  'checked',
  'clickable',
  'closed',
  'collapsed',
  'commands',
  'completed',
  'copied',
  'current',
  'day-selected',
  'default',
  'disabled',
  'dragged',
  'dragging',
  'dragging-hue',
  'dragging-in-area',
  'elevated',
  'ellipsis',
  'empty',
  'enabled',
  'error',
  'expanded',
  'fallback-icon',
  'fallback-text',
  'filled',
  'filtered',
  'focused',
  'full',
  'fullscreen',
  'glass',
  'hidden',
  'hover',
  'hover-preview',
  'hovered',
  'idle',
  'image',
  'inactive-dot',
  'invalid-hex (error)',
  'item-hovered',
  'item-selected',
  'loaded',
  'loading',
  'no-published-inset (pass-through)',
  'no-scroll (nothing painted)',
  'normal',
  'nothing-picked',
  'off',
  'offline',
  'on',
  'online',
  'open',
  'other',
  'out-of-range (disabled)',
  'outlined',
  'page',
  'panel-open',
  'partial',
  'preset-active',
  'pressed',
  'range-closed',
  'read-only',
  'resizing',
  'rest',
  'results',
  'row-selected',
  'searching',
  'selected',
  'sorted',
  'split',
  'stacked',
  'start-only',
  'step-active',
  'step-done',
  'step-pending',
  'streaming',
  'tab-active',
  'tab-hovered',
  'tab-inactive',
  'today',
  'top-hidden',
  'unchecked',
  'unselected',
  'upcoming',
  'valid-hex',
  'visible',
  'with-action',
  'with-ancestor (switches off)',
  'with-banner',
  'with-ephemeral-sheet-above',
  'with-inset (applies and consumes)',
  'without-ancestor (pass-through)',
  'year-month-grid',
};

/// Variações aceitas em `AppComponentMeta.variants`.
const Set<String> kComponentVariants = <String>{
  'asset',
  'badge',
  'bordered',
  'checkbox',
  'circle',
  'confirmation',
  'danger',
  'delete',
  'desktop',
  'edge.end',
  'edge.start',
  'elevated',
  'error',
  'filled',
  'flat',
  'generic',
  'get',
  'glass',
  'grouped',
  'head',
  'horizontal',
  'icon+label',
  'icon-only',
  'info',
  'l',
  'lift',
  'm',
  'mobile',
  'multipleChoice',
  'navigation',
  'network',
  'neutral',
  'none',
  'options',
  'outlined',
  'patch',
  'pop',
  'post',
  'primary',
  'put',
  'raised',
  'rotate',
  's',
  'scale',
  'singleChoice',
  'square',
  'success',
  'text-only',
  'toggle',
  'vertical',
  'warning',
  'xl',
};
